import styles from "./globals.css"
import Header from "./Components/Header/page.jsx";
import Footer from "@/app/Components/Footer/page";




export const metadata = {
    title: 'Create Next app',
    description: 'Generated by create _next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <Header />
        <main>{children}</main>
        <Footer />
        </body>
        </html>
    )
}
